// Site data - placeholder/demo content

export const SITE_CONFIG = {
  name: "Park Lane Motorcycles",
  tagline: "Where Passion Meets the Road",
  phone: "01634 712345",
  logo: "/images/logo/placeholder.svg",
  logoIcon: "/images/logo/placeholder.svg",
  images: {
    logo: "/images/logo/placeholder.svg",
    logoIcon: "/images/logo/placeholder.svg",
    hero: "/images/downthemall/about-first-2.jpg",
    heroSlides: [
      "https://kovemotouk.com/wp-content/uploads/2026/01/Ultra-Bee-5.jpg",
      "https://kovemotouk.com/wp-content/uploads/2025/12/Kove-800X-Touring-Large-scaled.jpg",
      "https://kovemotouk.com/wp-content/uploads/2025/10/800X-RALLY-GOLD_14-scaled.jpg",
      "https://kovemotouk.com/wp-content/uploads/2026/01/Kove-Compressed.png",
      "/images/downthemall/kove-about.1767193342.jpg",
    ],
    workshop: "/images/downthemall/about-first-2.jpg",
    /** Expert Servicing cards - distinct from about images */
    workshopServiceImages: [
      "/images/downthemall/kove-about.1767193342.jpg", // Servicing - dealership
      "https://kovemotouk.com/wp-content/uploads/2026/01/Ultra-Bee-5.jpg", // MOT - 800X Pro
      "https://kovemotouk.com/wp-content/uploads/2025/12/Kove-800X-Touring-Large-scaled.jpg", // Diagnostics - Touring
      "https://kovemotouk.com/wp-content/uploads/2025/10/800X-RALLY-GOLD_14-scaled.jpg", // Tyres - Rally
    ],
    adventure: "/images/downthemall/about-second-1.jpg",
    sport: "/images/downthemall/about-second-2.jpg",
    classic: "/images/downthemall/about-second-3.jpg",
    kove: "/images/downthemall/kove-about.1767193342.jpg",
    /** Official KOVE bike photos from kovemotouk.com */
    koveBikePhotos: [
      "https://kovemotouk.com/wp-content/uploads/2026/01/Kove-Compressed.png", // 450 Rally
      "https://kovemotouk.com/wp-content/uploads/2026/01/Ultra-Bee-5.jpg", // 800X Pro
      "https://kovemotouk.com/wp-content/uploads/2025/12/Kove-800X-Touring-Large-scaled.jpg", // 800X Touring
      "https://kovemotouk.com/wp-content/uploads/2025/10/800X-RALLY-GOLD_14-scaled.jpg", // 800X Rally
    ],
    /** Bright hero image for KOVE pages - 800X Rally Gold shows bike clearly */
    koveHero: "https://kovemotouk.com/wp-content/uploads/2025/10/800X-RALLY-GOLD_14-scaled.jpg",
    about: [
      "/images/downthemall/about-first-1.jpg",
      "/images/downthemall/about-first-2.jpg",
      "/images/downthemall/about-first-3.jpg",
      "/images/downthemall/about-second-1.jpg",
      "/images/downthemall/about-second-2.jpg",
      "/images/downthemall/about-second-3.jpg",
    ],
    /** Find Your Budget - bike images matching each tier */
    budgetBoxes: [
      "/images/bikes/vehicles/7700890_1.jpg", // Up to £100 - KTM 390 Duke (starter)
      "/images/bikes/vehicles/7707550_1.jpg", // Up to £150 - Versys 650 (middleweight)
      "/images/bikes/vehicles/7710804_1.jpg", // £200+ - Fireblade (premium)
    ],
    bodyStyleIcons: {
      cruiser: "/images/downthemall/cruiser.png",
      enduro: "/images/downthemall/enduro.png",
      naked: "/images/downthemall/naked.png",
      sportsbike: "/images/downthemall/sports-bike.png",
      adventure: "/images/downthemall/sports-tourer.png",
      tourer: "/images/downthemall/sports-tourer.png",
      scooter: "/images/downthemall/learner.png",
    },
    koveHeaders: [
      "/images/downthemall/kove-header.png",
      "/images/downthemall/kove-header(1).png",
      "/images/downthemall/kove-header(2).png",
      "/images/downthemall/kove-header(3).png",
      "/images/downthemall/kove-header(4).png",
      "/images/downthemall/kove-header(5).png",
      "/images/downthemall/kove-header(6).png",
      "/images/downthemall/kove-header(7).png",
      "/images/downthemall/kove-header(8).png",
      "/images/downthemall/kove-header(9).png",
      "/images/downthemall/kove-header(10).png",
    ],
    cutoutBike: "/images/downthemall/cutout_ryder_bike.png",
    tyreBrands: {
      michelin: "/images/downthemall/michelin-logo.svg",
      bridgestone: "/images/downthemall/bridgestone-logo.svg",
      continental: "/images/downthemall/continental-logo.svg",
    },
    partnerLogos: {
      closeBrothers: "/images/downthemall/close-brothers1.png",
      hpi: "/images/downthemall/hpi-crest.png",
    },
    brandLogos: {
      BENELLI: "/images/downthemall/benelli.png",
      BMW: "/images/downthemall/bmw.png",
      CCM: "/images/downthemall/ccm.png",
      DUCATI: "/images/downthemall/ducati.png",
      "HARLEY-DAVIDSON": "/images/downthemall/harley-davidson.png",
      HONDA: "/images/downthemall/honda-bike.png",
      HUSQVARNA: "/images/downthemall/husqvarna.png",
      KAWASAKI: "/images/downthemall/kawasaki.png",
      KOVE: "/images/downthemall/kove.png",
      KTM: "/images/downthemall/ktm.png",
      SUZUKI: "/images/downthemall/suzuki.png",
      TRIUMPH: "/images/downthemall/triumph.png",
      YAMAHA: "/images/downthemall/yamaha.png",
    },
    /** Selling/part-exchange hero images - distinct from about */
    sellingHeroes: [
      "/images/bikes/vehicles/7713789_1.jpg", // Norden 901
      "/images/downthemall/kove-about.1767193342.jpg", // Dealership
      "https://kovemotouk.com/wp-content/uploads/2026/01/Ultra-Bee-5.jpg", // KOVE 800X Pro
    ],
  },
  email: "enquiries@parklanemotorcycles.co.uk",
  address: {
    line1: "14 Industrial Way",
    line2: "Milton Regis",
    town: "Sittingbourne",
    county: "Kent",
    postcode: "ME9 8PH",
  },
  hours: [
    { day: "Monday", hours: "Closed" },
    { day: "Tuesday", hours: "09:00 – 17:00" },
    { day: "Wednesday", hours: "09:00 – 17:00" },
    { day: "Thursday", hours: "09:00 – 17:00" },
    { day: "Friday", hours: "09:00 – 17:00" },
    { day: "Saturday", hours: "09:00 – 17:00" },
    { day: "Sunday", hours: "Closed" },
  ],
  companyNo: "12345678",
  fcaNo: "987654",
  facebook: "https://www.facebook.com",
  coords: { lat: 51.3389, lng: 0.7389 },
  /** WhatsApp - UK format (44 + number without leading 0). Add to env: NEXT_PUBLIC_WHATSAPP */
  whatsapp: process.env.NEXT_PUBLIC_WHATSAPP || "441634712345",
  /** Formspree endpoint for form submissions. Create at formspree.io, add to .env: NEXT_PUBLIC_FORMSPREE_ENDPOINT */
  formEndpoint: process.env.NEXT_PUBLIC_FORMSPREE_ENDPOINT || "",
  /** Site base URL for sitemap/robots. Vercel sets VERCEL_URL. */
  baseUrl: process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "https://www.example.com",
  /** Previously sold archive */
  previouslySoldArchiveUrl: "",
  /** KOVE videos */
  koveVideos: [
    { id: "3lBTPeak8Fg", title: "KOVE 800X Pro Review", source: "youtube" },
    { id: "Z0ACWLg9aRc", title: "2025 KOVE 800X Review", source: "youtube" },
    { id: "wYvBTaQv0iU", title: "KOVE 800X Pro vs Tenere 700", source: "youtube" },
  ],
};

export const LATEST_BIKES = [
  {
    id: "7713789",
    slug: "used-husqvarna-norden-901-expedition-sittingbourne-kent-7713789",
    year: "2023",
    make: "HUSQVARNA",
    model: "Norden 901 Expedition",
    price: 9290,
    financeFrom: 168.89,
    mileage: "10,136",
    engineSize: "889cc",
    colour: "White",
    owners: 2,
    bodyStyle: "adventure",
    image: "/images/bikes/vehicles/7713789_1.jpg",
    images: ["/images/bikes/vehicles/7713789_1.jpg"],
    description:
      "GREAT SPEC, READY FOR ADVENTURE. This Husqvarna Norden 901 Expedition with Kriega OS Base is in very good condition, built for serious adventure, with 10,136 miles. Proper long-distance adventure spec with WP XPLOR suspension, heated seat & grips, cruise control, and full adventure equipment.",
    features: [
      "WP XPLOR 48mm fully adjustable forks (240mm travel)",
      "Cruise control",
      "Heated rider's seat & grips",
      "Colour TFT display",
      "Cornering ABS with Offroad mode",
      "Quickshifter+ (up & down)",
      "Tubeless spoked wheels",
      "Kriega OS base system",
      "Spot lights",
      "Heavy duty aluminium sump guard",
    ],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7710804",
    slug: "used-honda-cbr1000rr-fireblade-sittingbourne-kent-7710804",
    year: "2018",
    make: "HONDA",
    model: "CBR1000RR Fireblade",
    price: 8490,
    financeFrom: 154.21,
    mileage: "9,500",
    engineSize: "999cc",
    colour: "Red",
    owners: 1,
    bodyStyle: "sportsbike",
    image: "/images/bikes/vehicles/7710804_1.jpg",
    images: ["/images/bikes/vehicles/7710804_1.jpg"],
    description:
      "BUY ONLINE 24 HRS A DAY - FINANCE AVAILABLE - ALL TYPES OF CREDIT ACCEPTED. Honda's legendary superbike in superb condition.",
    features: ["999cc inline-four", "Full power mode", "ABS", "Traction control"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7707550",
    slug: "used-kawasaki-versys-650-sittingbourne-kent-7707550",
    year: "2021",
    make: "KAWASAKI",
    model: "Versys 650",
    price: 4290,
    financeFrom: 77.98,
    mileage: "8,200",
    engineSize: "649cc",
    colour: "Green",
    owners: 1,
    bodyStyle: "adventure",
    image: "/images/bikes/vehicles/7707550_1.jpg",
    images: ["/images/bikes/vehicles/7707550_1.jpg"],
    description:
      "A highly versatile middleweight adventure-tourer in excellent condition with low mileage.",
    features: ["649cc parallel twin", "Kawasaki Traction Control", "ABS", "Wind protection"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7700890",
    slug: "used-ktm-390-duke-sittingbourne-kent-7700890",
    year: "2016",
    make: "KTM",
    model: "390 Duke",
    price: 2490,
    financeFrom: 45.22,
    mileage: "12,300",
    engineSize: "373cc",
    colour: "Orange",
    owners: 2,
    bodyStyle: "naked",
    image: "/images/bikes/vehicles/7700890_1.jpg",
    images: ["/images/bikes/vehicles/7700890_1.jpg"],
    description:
      "The perfect A2-licence friendly naked bike. Punchy single-cylinder with great handling.",
    features: ["373cc single cylinder", "ABS", "Slipper clutch", "WP suspension"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7700796",
    slug: "used-ducati-hypermotard-1100-sittingbourne-kent-7700796",
    year: "2011",
    make: "DUCATI",
    model: "Hypermotard 1100 EVO",
    price: 5990,
    financeFrom: 108.85,
    mileage: "15,600",
    engineSize: "1078cc",
    colour: "Red",
    owners: 2,
    bodyStyle: "naked",
    image: "/images/bikes/vehicles/7700796_1.jpg",
    images: ["/images/bikes/vehicles/7700796_1.jpg"],
    description:
      "The iconic Ducati supermoto. Aggressive Testastretta engine with outrageous performance.",
    features: ["1078cc Testastretta L-twin", "DTC traction control", "Ohlins rear shock", "Marchesini wheels"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7700417",
    slug: "used-bmw-f-900-gs-sittingbourne-kent-7700417",
    year: "2024",
    make: "BMW",
    model: "F 900 GS",
    price: 9490,
    financeFrom: 172.53,
    mileage: "2,100",
    engineSize: "895cc",
    colour: "Blue",
    owners: 1,
    bodyStyle: "adventure",
    image: "/images/bikes/vehicles/7700417_1.jpg",
    images: ["/images/bikes/vehicles/7700417_1.jpg"],
    description:
      "Nearly new BMW F 900 GS. The most versatile middleweight GS in near-showroom condition.",
    features: ["895cc parallel twin", "Dynamic ESA", "ABS Pro", "Riding modes", "LED lighting"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7699355",
    slug: "used-yamaha-xsr900-sittingbourne-kent-7699355",
    year: "2022",
    make: "YAMAHA",
    model: "XSR900",
    price: 7590,
    financeFrom: 138.0,
    mileage: "5,900",
    engineSize: "888cc",
    colour: "Black",
    owners: 1,
    bodyStyle: "naked",
    image: "/images/bikes/vehicles/7699355_1.jpg",
    images: ["/images/bikes/vehicles/7699355_1.jpg"],
    description:
      "The retro-modern naked triple. Incredible CP3 engine with classic cafe racer styling.",
    features: ["888cc CP3 triple", "Quickshifter", "Traction control", "Slide control", "D-MODE"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7696336",
    slug: "used-bmw-r-1250-r-sittingbourne-kent-7696336",
    year: "2020",
    make: "BMW",
    model: "R 1250 R Exclusive",
    price: 9490,
    financeFrom: 172.53,
    mileage: "18,400",
    engineSize: "1254cc",
    colour: "Black",
    owners: 2,
    bodyStyle: "naked",
    image: "/images/bikes/vehicles/7696336_1.jpg",
    images: ["/images/bikes/vehicles/7696336_1.jpg"],
    description:
      "BMW's flagship naked roadster in Exclusive trim. ShiftCam technology and a mountain of standard equipment.",
    features: ["1254cc Boxer ShiftCam", "Dynamic ESA Pro", "Heated grips", "Riding modes", "TFT display"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7687285",
    slug: "used-benelli-leoncino-800-sittingbourne-kent-7687285",
    year: "2023",
    make: "BENELLI",
    model: "Leoncino 800 Trail",
    price: 4990,
    financeFrom: 90.68,
    mileage: "3,200",
    engineSize: "754cc",
    colour: "Green",
    owners: 1,
    bodyStyle: "adventure",
    image: "/images/bikes/vehicles/7687285_1.jpg",
    images: ["/images/bikes/vehicles/7687285_1.jpg"],
    description:
      "Near new Benelli Leoncino 800 Trail. Italian style, brilliant value, excellent condition.",
    features: ["754cc parallel twin", "ABS", "Traction control", "Adjustable suspension", "Off-road capability"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7670723",
    slug: "used-triumph-tiger-800-sittingbourne-kent-7670723",
    year: "2015",
    make: "TRIUMPH",
    model: "Tiger 800 XRx",
    price: 5290,
    financeFrom: 96.12,
    mileage: "22,000",
    engineSize: "799cc",
    colour: "Crystal White",
    owners: 2,
    bodyStyle: "adventure",
    image: "/images/bikes/vehicles/7670723_1.jpg",
    images: ["/images/bikes/vehicles/7670723_1.jpg"],
    description:
      "Triumph's legendary adventure tourer. XRx road-biased spec with a wealth of equipment.",
    features: ["799cc triple", "ABS", "Traction control", "Riding modes", "Off-road ABS"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7657656",
    slug: "used-honda-cbr650f-sittingbourne-kent-7657656",
    year: "2015",
    make: "HONDA",
    model: "CBR650F",
    price: 2990,
    financeFrom: 54.32,
    mileage: "18,500",
    engineSize: "649cc",
    colour: "Red",
    owners: 2,
    bodyStyle: "sportsbike",
    image: "/images/bikes/vehicles/7657656_1.jpg",
    images: ["/images/bikes/vehicles/7657656_1.jpg"],
    description:
      "Versatile middleweight sportsbike in great condition. A2-licence friendly with full power mode.",
    features: ["649cc inline-four", "ABS", "Sporty ergonomics", "Excellent fuel economy"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7657643",
    slug: "used-triumph-street-twin-sittingbourne-kent-7657643",
    year: "2017",
    make: "TRIUMPH",
    model: "Street Twin",
    price: 4590,
    financeFrom: 83.41,
    mileage: "14,200",
    engineSize: "900cc",
    colour: "Jet Black",
    owners: 2,
    bodyStyle: "cruiser",
    image: "/images/bikes/vehicles/7657643_1.jpg",
    images: ["/images/bikes/vehicles/7657643_1.jpg"],
    description:
      "Triumph's iconic modern classic. 900cc high-torque twin with timeless Bonneville styling.",
    features: ["900cc water-cooled parallel twin", "ABS", "Riding modes", "Low seat height", "Classic styling"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7654167",
    slug: "used-ccm-spitfire-sittingbourne-kent-7654167",
    year: "2021",
    make: "CCM",
    model: "Spitfire Blackout",
    price: 7750,
    financeFrom: 140.82,
    mileage: "1,200",
    engineSize: "450cc",
    colour: "Matte Black",
    owners: 1,
    bodyStyle: "naked",
    image: "/images/bikes/vehicles/7654167_1.jpg",
    images: ["/images/bikes/vehicles/7654167_1.jpg"],
    description:
      "Ultra-rare British-built CCM Spitfire Blackout. Bespoke, hand-crafted, and nearly new.",
    features: ["450cc single cylinder", "Hand-built in Bolton", "Öhlins suspension", "Brembo brakes", "Carbon fibre parts"],
    warranty: "3 months (extendable to 3 years)",
  },
  {
    id: "7648278",
    slug: "used-bmw-r-1250-rs-sittingbourne-kent-7648278",
    year: "2021",
    make: "BMW",
    model: "R 1250 RS",
    price: 9490,
    financeFrom: 172.53,
    mileage: "16,800",
    engineSize: "1254cc",
    colour: "Black Storm Metallic",
    owners: 1,
    bodyStyle: "sportsbike",
    image: "/images/bikes/vehicles/7648278_1.jpg",
    images: ["/images/bikes/vehicles/7648278_1.jpg"],
    description:
      "BMW's sports-tourer Boxer. ShiftCam technology, full electronics suite, and dynamic fairing.",
    features: ["1254cc Boxer ShiftCam", "Dynamic ESA", "Heated grips", "Keyless ride", "TFT display"],
    warranty: "3 months (extendable to 3 years)",
  },
];

export const MAKES = [
  "BENELLI", "BMW", "CCM", "DUCATI", "HARLEY-DAVIDSON",
  "HONDA", "HUSQVARNA", "KAWASAKI", "KOVE", "KTM",
  "SUZUKI", "TRIUMPH", "YAMAHA",
];

export const BODY_STYLES = [
  { label: "L-Plates & Scooters", value: "scooter", icon: "🛵" },
  { label: "Naked", value: "naked", icon: "⚡" },
  { label: "Sportsbike", value: "sportsbike", icon: "🏁" },
  { label: "Adventure & Tourers", value: "adventure", icon: "🌍" },
  { label: "Cruiser", value: "cruiser", icon: "🛣️" },
  { label: "Trail & Enduro", value: "enduro", icon: "🏔️" },
];

export const SERVICE_PRICES = {
  oilService: [
    { size: "Up to 125cc", price: 55 },
    { size: "126cc to 500cc", price: 70 },
    { size: "501cc to 900cc", price: 85 },
    { size: "900cc+", price: 95 },
  ],
  fullService: [
    { brand: "All Brands (125cc)", base: 125, interim: 165, full: 252 },
    { brand: "Honda, Kawasaki, Suzuki, Yamaha, Triumph (Single & Twin)", base: 139, interim: 179, full: 299 },
    { brand: "Honda, Kawasaki, Suzuki, Yamaha, Triumph (Triple & Four Cyl.)", base: 149, interim: 209, full: 379 },
    { brand: "Harley Davidson & Victory", base: 169, interim: 239, full: 319 },
    { brand: "Aprilia, BMW, Ducati, KTM", base: 179, interim: 249, full: 419 },
  ],
  tyres: {
    fitBalanceLoose: 20,
    fitBalanceRideIn: 24,
  },
  mot: 29.65,
  diagnostics: 42,
  serviceLight: 25,
  additional: [
    { service: "Brake Fluid", upTo125: 45, to500: 50, to900: 55, over900: 55 },
    { service: "Coolant Change", upTo125: 45, to500: 50, to900: 60, over900: 60 },
    { service: "Fork Seal Replacement", upTo125: 135, to500: 145, to900: 195, over900: 195 },
    { service: "Diagnostics", upTo125: 42, to500: 42, to900: 42, over900: 42 },
    { service: "Chain & Sprockets", upTo125: 112, to500: 174, to900: 219, over900: 235 },
  ],
};

/** Sold bike images from public/images/sold */
const SOLD_IMAGES = [
  "/images/sold/142506098.jpg", "/images/sold/152643413.jpg", "/images/sold/162958573.jpg", "/images/sold/165436716.jpg", "/images/sold/165486038.jpg",
  "/images/sold/166434074.jpg", "/images/sold/168021593.jpg", "/images/sold/168583654.jpg", "/images/sold/168601710.jpg", "/images/sold/168893127.jpg",
  "/images/sold/169189285.jpg", "/images/sold/169383102.jpg", "/images/sold/169526208.jpg", "/images/sold/169533423.jpg", "/images/sold/169533479.jpg",
  "/images/sold/170529709.jpg", "/images/sold/170941288.jpg", "/images/sold/171204319.jpg", "/images/sold/171898839.jpg", "/images/sold/171996803.jpg",
  "/images/sold/171998010.jpg", "/images/sold/172048714.jpg", "/images/sold/172216164.jpg", "/images/sold/172683964.jpg", "/images/sold/172685824.jpg",
  "/images/sold/172817718.jpg", "/images/sold/172902813.jpg", "/images/sold/173302664.jpg", "/images/sold/173352464.jpg", "/images/sold/173725794.jpg",
  "/images/sold/173727628.jpg", "/images/sold/173727825.jpg", "/images/sold/173727910.jpg", "/images/sold/173796161.jpg", "/images/sold/173898817.jpg",
  "/images/sold/173976013.jpg", "/images/sold/174052873.jpg", "/images/sold/174053421.jpg", "/images/sold/174053765.jpg", "/images/sold/174053972.jpg",
  "/images/sold/174353393.jpg", "/images/sold/174356416.jpg", "/images/sold/174514602.jpg", "/images/sold/174519647.jpg", "/images/sold/174520403.jpg",
  "/images/sold/174521886.jpg", "/images/sold/174530161.jpg", "/images/sold/174533730.jpg", "/images/sold/174574764.jpg", "/images/sold/174581448.jpg",
];

/** Sample of previously sold bikes */
export const PREVIOUSLY_SOLD = [
  { year: "2024", make: "Harley-Davidson", model: "Pan America SPECIAL", image: SOLD_IMAGES[0] },
  { year: "2023", make: "Ducati", model: "Monster 937", image: SOLD_IMAGES[1] },
  { year: "2023", make: "Ducati", model: "Desertx", image: SOLD_IMAGES[2] },
  { year: "2023", make: "Kawasaki", model: "Ninja 1000sx", image: SOLD_IMAGES[3] },
  { year: "2023", make: "Aprilia", model: "SR GT 125", image: SOLD_IMAGES[4] },
  { year: "2022", make: "BMW", model: "R 1250 GS Trophy Edition", image: SOLD_IMAGES[5] },
  { year: "2021", make: "Ducati", model: "Multistrada V4 S Sport", image: SOLD_IMAGES[6] },
  { year: "2021", make: "Ford", model: "Kuga 2.0 EcoBlue ST-Line X", image: SOLD_IMAGES[7] },
  { year: "2020", make: "Yamaha", model: "Tracer 700", image: SOLD_IMAGES[8] },
  { year: "2020", make: "Honda", model: "NC750x", image: SOLD_IMAGES[9] },
  { year: "2019", make: "BMW", model: "R 1250 GS Adventure", image: SOLD_IMAGES[10] },
  { year: "2019", make: "BMW", model: "R 1250 GS Exclusive TE", image: SOLD_IMAGES[11] },
  { year: "2019", make: "Ducati", model: "Multistrada 950", image: SOLD_IMAGES[12] },
  { year: "2019", make: "KTM", model: "1290 Super Adventure S", image: SOLD_IMAGES[13] },
  { year: "2019", make: "Suzuki", model: "V-Strom 650 X", image: SOLD_IMAGES[14] },
  { year: "2019", make: "Triumph", model: "Tiger 800 XRx Low", image: SOLD_IMAGES[15] },
  { year: "2019", make: "Yamaha", model: "MT-07", image: SOLD_IMAGES[16] },
  { year: "2018", make: "Honda", model: "CBR1000RR Fireblade", image: SOLD_IMAGES[17] },
  { year: "2018", make: "Suzuki", model: "GSX-S750", image: SOLD_IMAGES[18] },
  { year: "2018", make: "Suzuki", model: "GSX-S1000f", image: SOLD_IMAGES[19] },
  { year: "2018", make: "BMW", model: "S 1000 R Sport", image: SOLD_IMAGES[20] },
  { year: "2017", make: "Honda", model: "CRF1000L Africa Twin DCT", image: SOLD_IMAGES[21] },
  { year: "2017", make: "Honda", model: "NC750x", image: SOLD_IMAGES[22] },
  { year: "2017", make: "KTM", model: "1290 Super Duke GT", image: SOLD_IMAGES[23] },
  { year: "2017", make: "Ducati", model: "Multistrada 950", image: SOLD_IMAGES[24] },
  { year: "2017", make: "Harley-Davidson", model: "Sportster XL1200 Forty Eight", image: SOLD_IMAGES[25] },
  { year: "2016", make: "Triumph", model: "Tiger 800 XRx", image: SOLD_IMAGES[26] },
  { year: "2016", make: "Honda", model: "CRF250L", image: SOLD_IMAGES[27] },
  { year: "2015", make: "Triumph", model: "Speed Triple 1050 94R Special Edition", image: SOLD_IMAGES[28] },
  { year: "2015", make: "Triumph", model: "Explorer", image: SOLD_IMAGES[29] },
  { year: "2015", make: "Kawasaki", model: "ZZR1400", image: SOLD_IMAGES[30] },
  { year: "2015", make: "Honda", model: "CB500x", image: SOLD_IMAGES[31] },
  { year: "2014", make: "BMW", model: "R 1200 GS", image: SOLD_IMAGES[32] },
  { year: "2014", make: "Triumph", model: "Explorer XC", image: SOLD_IMAGES[33] },
  { year: "2013", make: "BMW", model: "F 700 GS", image: SOLD_IMAGES[34] },
  { year: "2013", make: "Triumph", model: "Explorer", image: SOLD_IMAGES[35] },
  { year: "2012", make: "BMW", model: "K 1600 GT", image: SOLD_IMAGES[36] },
  { year: "2011", make: "Ducati", model: "M696+", image: SOLD_IMAGES[37] },
  { year: "2009", make: "Kawasaki", model: "Versys 650", image: SOLD_IMAGES[38] },
  { year: "2007", make: "BMW", model: "R 1200 GS", image: SOLD_IMAGES[39] },
  { year: "2005", make: "Suzuki", model: "GSX1400", image: SOLD_IMAGES[40] },
  { year: "2005", make: "Aprilia", model: "RSV Mille R Factory", image: SOLD_IMAGES[41] },
  { year: "2003", make: "Kawasaki", model: "Ninja ZX-6R", image: SOLD_IMAGES[42] },
  { year: "2001", make: "Triumph", model: "Tiger 955i", image: SOLD_IMAGES[43] },
  { year: "2001", make: "Yamaha", model: "R1", image: SOLD_IMAGES[44] },
  { year: "2001", make: "Aprilia", model: "RSV Mille", image: SOLD_IMAGES[45] },
];

export const REVIEWS = [
  {
    author: "Ian Cogger",
    rating: 5,
    text: "Fantastic service from this family run business. I purchased a beautiful Triumph Thruxton from them and it has been a dream — no problems. Whenever it comes to trade it in, they will be my first point of call.",
  },
  {
    author: "Gary Lloyd",
    rating: 5,
    text: "Great company to deal with, always fair and honourable. I will always come back for a deal on my next bike. Thanks Joe, you're the best.",
  },
  {
    author: "Sarah T.",
    rating: 5,
    text: "Bought my first bike from here and the team made the whole process so easy. Joe explained everything and found me perfect finance. Would highly recommend.",
  },
  {
    author: "Mark D.",
    rating: 5,
    text: "Brilliant workshop. Had my BMW in for a full service — professional, transparent pricing, and done on time. No hidden charges whatsoever.",
  },
];
